### ISSUE TITLE
binding does not appear in console

### ISSUE THREAD

**Issue by jrcourtois** [aleon-GmbH/aleoncean-openhab-binding#9]
I downloaded the source and build them without using Eclipse but directly in console.
I copied the jar generated in the addons folder and as I start openhab (1.7) it does not appear in the list.

I tried to look for the bundles and as it is present tried to start it.

 ```
78	Active		org.openhab.binding.http			org.openhab.binding.http(bid=222)
79	Active		org.openhab.persistence.exec			org.openhab.persistence.exec(bid=224)
80	Active		org.openhab.binding.ntp.binding			org.openhab.binding.ntp(bid=225)
81	Active		org.openhab.binding.ntp.genericbindingprovider			org.openhab.binding.ntp(bid=225)
82	Active		org.openhab.persistence.logging			org.openhab.persistence.logging(bid=226)
osgi> bundles aleoncean
org.openhab.binding.aleoncean_1.7.3 [223]
  Id=223, Status=INSTALLED   Data Root=/Users/jr/openhab/openhab1.8/server/configuration/org.eclipse.osgi/bundles/223/data  "No registered services."
  No services in use.
osgi> start 223
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at org.eclipse.equinox.console.commands.EquinoxCommandsConverter.convert(EquinoxCommandsConverter.java:61)
	at org.apache.felix.gogo.runtime.CommandProcessorImpl.convert(CommandProcessorImpl.java:254)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.convert(CommandSessionImpl.java:374)
	at org.apache.felix.gogo.runtime.Reflective.coerce(Reflective.java:389)
	at org.apache.felix.gogo.runtime.Reflective.coerce(Reflective.java:310)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:110)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Console.run(Console.java:62)
	at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
	at java.lang.Thread.run(Thread.java:744)
gogo: BundleException: The bundle "org.openhab.binding.aleoncean_1.7.3 [223]" could not be resolved. Reason: Missing Constraint: Import-Package: eu.aleon.aleoncean.device; version="[1.8.0,2.0.0)"
```

By copying the aleoncean.jar in the addons folder makes me have another missing Constraint : org.osgi.framework...
I think I am not building the jar the right way, but can not find how to build it properly.

**Comment by maggu2810** [comment]
I do not use OH1 myself (I am using OH2 and OH1 bundles).

The first message is normal. The openhab aleoncean binding bundle does import the aleoncean library.
So, the OSGi framework does need that bundle (the bundle of the aleoncean library), to resolve the openhab binding.

To solve the next missing constraint, we have to look at the bundle imports of the openhab binding and the bundles that are present in your OSGi container.

Perhaps we refer to a more up to date OSGi framework then OH1 offers.

**Comment by maggu2810** [comment]
Okay, it is easy to change the org.osgi.framework requirements.
But for the service I am using OSGi annotations and so I need at least OSGi compendium release 5.
openHAB 1 is using 4.2 (if I see it correctly).
I don't believe openHAB 1 will change this, so I think the "easiest" way would be if you are using openHAB 2 and the compatibility layer for openHAB 1 bundles (already present in the "standard" openHAB 2 runtime).

Okay?

**Comment by maggu2810** [comment]
I don't commit the changes for the org.osgi.framework requirements.
The component annotations has been part of the compendium starting with release 4.3.
So we can use annotations (exclusive) OR we can set the compendium requirements to 4.2.
I don't like to drop the annotation usage (at least upstream).

Sorry, for the trouble. I added a note to the README of that project.

**Comment by jrcourtois** [comment]
Thanks for your answer. Seems ok in OH 2

**Comment by maggu2810** [comment]
So, could we close that issue? All fine?

**Comment by jrcourtois** [comment]
all fine.
